# SPDX-FileCopyrightText: : 2022 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: CC0-1.0

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: fix-encoding-pragma

# Formatting with "black" coding style
-   repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
    # Format Python files
    -   id: black
    # Format Jupyter Python notebooks
    -   id: black-jupyter

# Use yamllint to check for valid YAML files and list syntax errors
- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.26.3
  hooks:
      - id: yamllint
        args: [--format, parsable, -c=.yamllint]

# Use yamlfmt to for formatting YAML files, something yamllint doesn't support
- repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
  rev: 0.1.0
  hooks:
      - id: yamlfmt
        args: [--mapping, '2',    # Indentation by 2 spaces
               --preserve-quotes, # Prevent parsing of e.g. Norway "NO" != False == NO
               --implicit_start,  # Add no start marker to YAML files
              ]

# Check for FSFE REUSE compliance (licensing)
-   repo: https://github.com/fsfe/reuse-tool
    rev: v0.14.0
    hooks:
    -   id: reuse