# SPDX-FileCopyrightText: : 2022 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: CC0-1.0

exclude: "^LICENSES"

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: check-merge-conflict
  - id: check-yaml
  - id: end-of-file-fixer
  - id: fix-encoding-pragma

# Formatting with "black" coding style
- repo: https://github.com/psf/black
  rev: 21.12b0
  hooks:
  # Format Python files
  - id: black
  # Format Jupyter Python notebooks
  - id: black-jupyter

# Use yamllint to check for valid YAML files and list syntax errors
- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.26.3
  hooks:
  - id: yamllint
    args: [--format, parsable, -c=.yamllint]

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.2.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2', --preserve-quotes]

# Format Snakemake rule / workflow files
-   repo: https://github.com/snakemake/snakefmt
    rev: 0.4.4
    hooks:
      - id: snakefmt

# Check for FSFE REUSE compliance (licensing)
- repo: https://github.com/fsfe/reuse-tool
  rev: v0.14.0
  hooks:
  - id: reuse
