# SPDX-FileCopyrightText: : 2017-2021 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: CC0-1.0

tutorial: true

scenario:
  clusters: [5]
  opts: [Co2L-24H]

countries: ['DE']

snapshots:
  start: "2013-03-01"
  end: "2013-04-01"
  closed: 'left' # end is not inclusive

electricity:
  co2limit: 100.e+6

  extendable_carriers:
    Generator: [OCGT]

  conventional_carriers: [coal, CCGT] # [nuclear, oil, OCGT, CCGT, coal, lignite, geothermal, biomass]

atlite:
  cutouts:
    europe-2013-era5-tutorial:
      module: era5
      x: [4., 15.]
      y: [46., 56.]
      time: ["2013-03", "2013-03"]

renewable:
  onwind:
    cutout: europe-2013-era5-tutorial
  offwind-ac:
    cutout: europe-2013-era5-tutorial
  offwind-dc:
    cutout: europe-2013-era5-tutorial
    max_depth: None
  solar:
    cutout: europe-2013-era5-tutorial

solving:
  options:
    solver_name: cbc
    min_iterations: 1
    max_iterations: 1
