# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: : 2017-2023 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: MIT

# This file is used to define the scenarios that are run by snakemake. Each entry on the first level is a scenario. Each scenario can contain configuration overrides with respect to the config/config.yaml settings.
#
# Example
#
# custom-scenario: # name of the scenario
#   electricity:
#       renewable_carriers: [wind, solar] # override the list of renewable carriers



fast:
  sector:
    logistic_curve: false

base:
  sector:
    car_reg_factor: 0.5
    logistic_curve: false

base-t:
  sector:
    car_reg_factor:
      2025: 0.5
      2030: 0.5
      2035: 0.8
      2040: 1.0
      2050: 1.0
    logistic_curve: false

slow:
  sector:
    logistic_curve: true

high-demand:
  sector:
    car_reg_factor: 0.5
    logistic_curve: false
    vary_demand:
      land transport demand heavy:
        2020: 1.05
        2025: 1.05 # compared to 2019 from Eurostat
        2030: 1.1
        2035: 1.15
        2040: 1.2
        2045: 1.25
        2050: 1.3
      land transport demand light:
        2020: 1.1
        2025: 1.05 # compared to 2019 from Eurostat
        2030: 1.1
        2035: 1.15
        2040: 1.2
        2045: 1.25
        2050: 1.3

low-demand:
  sector:
    car_reg_factor: 0.5
    logistic_curve: false
    vary_demand:
      land transport demand heavy:
        2020: 1.0
        2025: 0.95 # compared to 2019 from Eurostat
        2030: 0.9
        2035: 0.85
        2040: 0.8
        2045: 0.75
        2050: 0.7
      land transport demand light:
        2020: 1.0
        2025: 0.95 # compared to 2019 from Eurostat
        2030: 0.9
        2035: 0.85
        2040: 0.8
        2045: 0.75
        2050: 0.7

high-elec-efficiency:
  sector:
    vary:
      Link:
        land transport EV light:
          efficiency: 1.25  # this should be roughly 150 kWh/100km
