# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: : 2017-2023 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: MIT

# This file is used to define the scenarios that are run by snakemake. Each entry on the first level is a scenario. Each scenario can contain configuration overrides with respect to the config/config.yaml settings.
#
# Example
#
# custom-scenario: # name of the scenario
#   electricity:
#       renewable_carriers: [wind, solar] # override the list of renewable carriers



fast:
  sector:
    car_reg_factor:
      light:
        2025: 0.3  # in 2023 around 15.72% EV share https://www.statista.com/statistics/500546/share-of-fuel-types-of-passenger-car-fleet-in-europe-by-country/
        2030: 1.0
        2035: 1.2
        2040: 1.2
        2050: 1.2
      heavy:
        2025: 0.3  # in 2023 around 15.72% EV share https://www.statista.com/statistics/500546/share-of-fuel-types-of-passenger-car-fleet-in-europe-by-country/
        2030: 1.0
        2035: 1.2
        2040: 1.2
        2050: 1.2
    vary:
      Link:
        land transport EV heavy:
          lifetime: 0.6
        BEV charger heavy:
          lifetime: 0.6
        BEV charger light:
          lifetime: 0.6
        land transport EV light:
          lifetime: 0.6
        land transport fuel cell heavy:
          lifetime: 0.6
        land transport fuel cell light:
          lifetime: 0.6
        land transport oil heavy:
          lifetime: 0.6
        land transport oil light:
          lifetime: 0.6

fast-p2:
  sector:
    car_reg_factor:
      light:
        2025: 0.3  # in 2023 around 15.72% EV share https://www.statista.com/statistics/500546/share-of-fuel-types-of-passenger-car-fleet-in-europe-by-country/
        2030: 1.0
        2035: 1.2
        2040: 1.2
        2050: 1.2
      heavy:
        2025: 0.3  # in 2023 around 15.72% EV share https://www.statista.com/statistics/500546/share-of-fuel-types-of-passenger-car-fleet-in-europe-by-country/
        2030: 1.0
        2035: 1.2
        2040: 1.2
        2050: 1.2
    vary:
      Link:
        land transport EV heavy:
          lifetime: 0.6
          capital_cost: 0.8
        BEV charger heavy:
          lifetime: 0.6
        BEV charger light:
          lifetime: 0.6
        land transport EV light:
          lifetime: 0.6
          capital_cost: 0.8
        land transport fuel cell heavy:
          lifetime: 0.6
          capital_cost: 1.2
        land transport fuel cell light:
          lifetime: 0.6
          capital_cost: 1.2
        land transport oil heavy:
          lifetime: 0.6
        land transport oil light:
          lifetime: 0.6

fast-p1:
  sector:
    car_reg_factor:
      light:
        2025: 0.3  # in 2023 around 15.72% EV share https://www.statista.com/statistics/500546/share-of-fuel-types-of-passenger-car-fleet-in-europe-by-country/
        2030: 1.0
        2035: 1.2
        2040: 1.2
        2050: 1.2
      heavy:
        2025: 0.3  # in 2023 around 15.72% EV share https://www.statista.com/statistics/500546/share-of-fuel-types-of-passenger-car-fleet-in-europe-by-country/
        2030: 1.0
        2035: 1.2
        2040: 1.2
        2050: 1.2
    vary:
      Link:
        land transport EV heavy:
          lifetime: 0.6
          capital_cost: 0.9
        BEV charger heavy:
          lifetime: 0.6
        BEV charger light:
          lifetime: 0.6
        land transport EV light:
          lifetime: 0.6
          capital_cost: 0.9
        land transport fuel cell heavy:
          lifetime: 0.6
          capital_cost: 1.1
        land transport fuel cell light:
          lifetime: 0.6
          capital_cost: 1.1
        land transport oil heavy:
          lifetime: 0.6
        land transport oil light:
          lifetime: 0.6

fast-m2:
  sector:
    car_reg_factor:
      light:
        2025: 0.3  # in 2023 around 15.72% EV share https://www.statista.com/statistics/500546/share-of-fuel-types-of-passenger-car-fleet-in-europe-by-country/
        2030: 1.0
        2035: 1.2
        2040: 1.2
        2050: 1.2
      heavy:
        2025: 0.3  # in 2023 around 15.72% EV share https://www.statista.com/statistics/500546/share-of-fuel-types-of-passenger-car-fleet-in-europe-by-country/
        2030: 1.0
        2035: 1.2
        2040: 1.2
        2050: 1.2
    vary:
      Link:
        land transport EV heavy:
          lifetime: 0.6
          capital_cost: 1.2
        BEV charger heavy:
          lifetime: 0.6
        BEV charger light:
          lifetime: 0.6
        land transport EV light:
          lifetime: 0.6
          capital_cost: 1.2
        land transport fuel cell heavy:
          lifetime: 0.6
          capital_cost: 0.8
        land transport fuel cell light:
          lifetime: 0.6
          capital_cost: 0.8
        land transport oil heavy:
          lifetime: 0.6
        land transport oil light:
          lifetime: 0.6

fast-m1:
  sector:
    car_reg_factor:
      light:
        2025: 0.3  # in 2023 around 15.72% EV share https://www.statista.com/statistics/500546/share-of-fuel-types-of-passenger-car-fleet-in-europe-by-country/
        2030: 1.0
        2035: 1.2
        2040: 1.2
        2050: 1.2
      heavy:
        2025: 0.3  # in 2023 around 15.72% EV share https://www.statista.com/statistics/500546/share-of-fuel-types-of-passenger-car-fleet-in-europe-by-country/
        2030: 1.0
        2035: 1.2
        2040: 1.2
        2050: 1.2
    vary:
      Link:
        land transport EV heavy:
          lifetime: 0.6
          capital_cost: 1.1
        BEV charger heavy:
          lifetime: 0.6
        BEV charger light:
          lifetime: 0.6
        land transport EV light:
          lifetime: 0.6
          capital_cost: 1.1
        land transport fuel cell heavy:
          lifetime: 0.6
          capital_cost: 0.9
        land transport fuel cell light:
          lifetime: 0.6
          capital_cost: 0.9
        land transport oil heavy:
          lifetime: 0.6
        land transport oil light:
          lifetime: 0.6

base:
  sector:
    logistic_curve: false


base-m1:
  sector:
    logistic_curve: false
    vary:
      Link:
        land transport EV heavy:
          capital_cost: 1.1
        land transport EV light:
          capital_cost: 1.1
        land transport fuel cell light:
          capital_cost: 0.9
        land transport fuel cell heavy:
          capital_cost: 0.9
  
base-m2:
  sector:
    logistic_curve: false
    vary:
      Link:
        land transport EV heavy:
          capital_cost: 1.2
        land transport EV light:
          capital_cost: 1.2
        land transport fuel cell light:
          capital_cost: 0.8
        land transport fuel cell heavy:
          capital_cost: 0.8


base-p1:
  sector:
    logistic_curve: false
    vary:
      Link:
        land transport EV heavy:
          capital_cost: 0.9
        land transport EV light:
          capital_cost: 0.9
        land transport fuel cell light:
          capital_cost: 1.1
        land transport fuel cell heavy:
          capital_cost: 1.1
  
base-p2:
  sector:
    logistic_curve: false
    vary:
      Link:
        land transport EV heavy:
          capital_cost: 0.8
        land transport EV light:
          capital_cost: 0.8
        land transport fuel cell light:
          capital_cost: 1.2
        land transport fuel cell heavy:
          capital_cost: 1.2

dsm:
  sector:
    bev_dsm: true


slow:
  sector:
    car_reg_factor:
      light:
        2025: 0.2  # in 2023 around 15.72% EV share https://www.statista.com/statistics/500546/share-of-fuel-types-of-passenger-car-fleet-in-europe-by-country/
        2030: 0.3
        2035: 0.5
        2040: 0.9
        2050: 1.0
      heavy:
        2025: 0.1  # in 2023 around 15.72% EV share https://www.statista.com/statistics/500546/share-of-fuel-types-of-passenger-car-fleet-in-europe-by-country/
        2030: 0.2
        2035: 0.3
        2040: 0.5
        2050: 0.9
    logistic_curve: false

slow-p1:
  sector:
    car_reg_factor:
      light:
        2025: 0.2  # in 2023 around 15.72% EV share https://www.statista.com/statistics/500546/share-of-fuel-types-of-passenger-car-fleet-in-europe-by-country/
        2030: 0.3
        2035: 0.5
        2040: 0.9
        2050: 1.0
      heavy:
        2025: 0.1  # in 2023 around 15.72% EV share https://www.statista.com/statistics/500546/share-of-fuel-types-of-passenger-car-fleet-in-europe-by-country/
        2030: 0.2
        2035: 0.3
        2040: 0.5
        2050: 0.9
    logistic_curve: false
    vary:
      Link:
        land transport EV heavy:
          capital_cost: 0.9
        land transport EV light:
          capital_cost: 0.9
        land transport fuel cell light:
          capital_cost: 1.1
        land transport fuel cell heavy:
          capital_cost: 1.1

slow-p2:
  sector:
    car_reg_factor:
      light:
        2025: 0.2  # in 2023 around 15.72% EV share https://www.statista.com/statistics/500546/share-of-fuel-types-of-passenger-car-fleet-in-europe-by-country/
        2030: 0.3
        2035: 0.5
        2040: 0.9
        2050: 1.0
      heavy:
        2025: 0.1  # in 2023 around 15.72% EV share https://www.statista.com/statistics/500546/share-of-fuel-types-of-passenger-car-fleet-in-europe-by-country/
        2030: 0.2
        2035: 0.3
        2040: 0.5
        2050: 0.9
    logistic_curve: false
    vary:
      Link:
        land transport EV heavy:
          capital_cost: 0.8
        land transport EV light:
          capital_cost: 0.8
        land transport fuel cell light:
          capital_cost: 1.2
        land transport fuel cell heavy:
          capital_cost: 1.2


slow-m2:
  sector:
    car_reg_factor:
      light:
        2025: 0.2  # in 2023 around 15.72% EV share https://www.statista.com/statistics/500546/share-of-fuel-types-of-passenger-car-fleet-in-europe-by-country/
        2030: 0.3
        2035: 0.5
        2040: 0.9
        2050: 1.0
      heavy:
        2025: 0.1  # in 2023 around 15.72% EV share https://www.statista.com/statistics/500546/share-of-fuel-types-of-passenger-car-fleet-in-europe-by-country/
        2030: 0.2
        2035: 0.3
        2040: 0.5
        2050: 0.9
    logistic_curve: false
    vary:
      Link:
        land transport EV heavy:
          capital_cost: 1.2
        land transport EV light:
          capital_cost: 1.2
        land transport fuel cell light:
          capital_cost: 0.8
        land transport fuel cell heavy:
          capital_cost: 0.8

slow-m1:
  sector:
    car_reg_factor:
      light:
        2025: 0.2  # in 2023 around 15.72% EV share https://www.statista.com/statistics/500546/share-of-fuel-types-of-passenger-car-fleet-in-europe-by-country/
        2030: 0.3
        2035: 0.5
        2040: 0.9
        2050: 1.0
      heavy:
        2025: 0.1  # in 2023 around 15.72% EV share https://www.statista.com/statistics/500546/share-of-fuel-types-of-passenger-car-fleet-in-europe-by-country/
        2030: 0.2
        2035: 0.3
        2040: 0.5
        2050: 0.9
    logistic_curve: false
    vary:
      Link:
        land transport EV heavy:
          capital_cost: 1.1
        land transport EV light:
          capital_cost: 1.1
        land transport fuel cell light:
          capital_cost: 0.9
        land transport fuel cell heavy:
          capital_cost: 0.9

          
high-demand:
  sector:
      vary_demand:
        land transport demand heavy:
          2020: 1.111
          2025: 1.166 # compared to 2019 from Eurostat
          2030: 1.221
          2035: 1.276
          2040: 1.331
          2045: 1.386
          2050: 1.441
        land transport demand light:
          2020: 1.1154
          2025: 1.17524 # compared to 2019 from Eurostat
          2030: 1.222694
          2035: 1.278464
          2040: 1.334234
          2045: 1.3900084
          2050: 1.668854

low-demand:
  sector:
    vary_demand:
      land transport demand heavy:
        2020: 1.0
        2025: 1.0 # compared to 2019 from Eurostat
        2030: 0.9
        2035: 0.85
        2040: 0.8
        2045: 0.75
        2050: 0.7
      land transport demand light:
        2020: 1.0
        2025: 1.0 # compared to 2019 from Eurostat
        2030: 0.9
        2035: 0.85
        2040: 0.8
        2045: 0.75
        2050: 0.7

high-elec-efficiency:
  sector:
    transport_electric_efficiency:
      # https://ev-database.org/de/cheatsheet/energy-consumption-electric-car
      # average energy consumption 188 Wh/km = 0.188 kWh/km = 18.8 kWh/100 km = 0.0188 MWh/ 100 km
      # 15 kWh/100 km = 0.015 MWh/100km => 1MWh = 66.66 * 100km
      # 1/0.188 -> 1 MWh = 53.19 * 100 km
      light: 66.66


logistic:
  sector:
    logistic_curve: true

high-DAC:
  sector:
    vary:
      Link:
        DAC:
          capital_cost: 1.5


h2-09:
  sector:
    vary:
      Link:
        land transport fuel cell heavy:
          capital_cost: 0.9
        land transport fuel cell light:
          capital_cost: 0.9

h2-08:
  sector:
    vary:
      Link:
        land transport fuel cell heavy:
          capital_cost: 0.8
        land transport fuel cell light:
          capital_cost: 0.8

h2-07:
  sector:
    vary:
      Link:
        land transport fuel cell heavy:
          capital_cost: 0.7
        land transport fuel cell light:
          capital_cost: 0.7

h2-11:
  sector:
    vary:
      Link:
        land transport fuel cell heavy:
          capital_cost: 1.1
        land transport fuel cell light:
          capital_cost: 1.1

h2-12:
  sector:
    vary:
      Link:
        land transport fuel cell heavy:
          capital_cost: 1.2
        land transport fuel cell light:
          capital_cost: 1.2

h2-13:
  sector:
    vary:
      Link:
        land transport fuel cell heavy:
          capital_cost: 1.3
        land transport fuel cell light:
          capital_cost: 1.3

elec-09:
  sector:
    vary:
      Link:
        land transport EV heavy:
          capital_cost: 0.9
        land transport EV light:
          capital_cost: 0.9

elec-08:
  sector:
    vary:
      Link:
        land transport EV heavy:
          capital_cost: 0.8
        land transport EV light:
          capital_cost: 0.8

elec-07:
  sector:
    vary:
      Link:
        land transport EV heavy:
          capital_cost: 0.7
        land transport EV light:
          capital_cost: 0.7

elec-11:
  sector:
    vary:
      Link:
        land transport EV heavy:
          capital_cost: 1.1
        land transport EV light:
          capital_cost: 1.1

elec-12:
  sector:
    vary:
      Link:
        land transport EV heavy:
          capital_cost: 1.2
        land transport EV light:
          capital_cost: 1.2

elec-13:
  sector:
    vary:
      Link:
        land transport EV heavy:
          capital_cost: 1.3
        land transport EV light:
          capital_cost: 1.3

elec-high-eff:
  sector:
    vary:
      Link:
        land transport EV heavy:
          efficiency: 1.2
        land transport EV light:
          efficiency: 1.2



h2-high-eff:
  sector:
    vary:
      Link:
        land transport fuel cell heavy:
          efficiency: 1.2
        land transport fuel cell light:
          efficiency: 1.2




biomass-hype:
  sector:
    vary:
      Store:
        solid biomass:
          e_initial: 2