# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: : 2017-2023 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: MIT

# This file is used to define the scenarios that are run by snakemake. Each entry on the first level is a scenario. Each scenario can contain configuration overrides with respect to the config/config.yaml settings.
#
# Example
#
# custom-scenario: # name of the scenario
#   electricity:
#       renewable_carriers: [wind, solar] # override the list of renewable carriers



fast:
  sector:
    logistic_curve: false

base:
  sector:
    car_reg_factor:
      2025: 0.2
      2030: 0.3
      2035: 1.0
      2040: 1.0
      2050: 1.0
    logistic_curve: false

base-t:
  sector:
    car_reg_factor:
      2025: 0.5
      2030: 0.5
      2035: 0.8
      2040: 1.0
      2050: 1.0
    logistic_curve: false

slow:
  sector:
    car_reg_factor:
      2025: 0.2
      2030: 0.2
      2035: 0.3
      2040: 0.3
      2050: 0.5
    logistic_curve: false

high-demand:
  sector:
    car_reg_factor: 0.5
    logistic_curve: false
    vary_demand:
      land transport demand heavy:
        2020: 1.05
        2025: 1.05 # compared to 2019 from Eurostat
        2030: 1.1
        2035: 1.15
        2040: 1.2
        2045: 1.25
        2050: 1.3
      land transport demand light:
        2020: 1.1
        2025: 1.05 # compared to 2019 from Eurostat
        2030: 1.1
        2035: 1.15
        2040: 1.2
        2045: 1.25
        2050: 1.3

low-demand:
  sector:
    car_reg_factor: 0.5
    logistic_curve: false
    vary_demand:
      land transport demand heavy:
        2020: 1.0
        2025: 0.95 # compared to 2019 from Eurostat
        2030: 0.9
        2035: 0.85
        2040: 0.8
        2045: 0.75
        2050: 0.7
      land transport demand light:
        2020: 1.0
        2025: 0.95 # compared to 2019 from Eurostat
        2030: 0.9
        2035: 0.85
        2040: 0.8
        2045: 0.75
        2050: 0.7

high-elec-efficiency:
  sector:
    car_reg_factor: 0.5
    logistic_curve: false
    transport_electric_efficiency:
      # https://ev-database.org/de/cheatsheet/energy-consumption-electric-car
      # average energy consumption 188 Wh/km = 0.188 kWh/km = 18.8 kWh/100 km = 0.0188 MWh/ 100 km
      # 15 kWh/100 km = 0.015 MWh/100km => 1MWh = 66.66 * 100km
      # 1/0.188 -> 1 MWh = 53.19 * 100 km
      light: 66.66


logistic:
  sector:
    logistic_curve: true

high-DAC:
  sector:
    vary:
      Link:
        DAC:
          capital_cost: 1.5
